#!/usr/bin/env php
<?php
/**
 * @file
 * Use helper commands to track contributions.
 */

require_once 'vendor/autoload.php';

use ContribLog\Console\Command\AddCommand;
use ContribLog\Console\Command\FormatCommand;
use ContribLog\Console\Command\GenerateCommand;
use ContribLog\Console\Command\LintCommand;
use Symfony\Component\Console\Application;

$console = new Application();
$console->add(new AddCommand);
$console->add(new FormatCommand);
$console->add(new GenerateCommand);
$console->add(new LintCommand);
$console->run();
