name: Contibutions CI
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v3
      -
        name: Validate composer configuration
        run: composer validate --strict
      -
        name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php-
      -
        name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress
      -
        name: Main script does not fail to start
        run: ./contriblog --help
      -
        name: Lint runs an example passes linting
        run: ./contriblog lint examples/contributions.yml
      -
        name: Can format and it is a no operation for the example
        run: |
          ./contriblog format examples/contributions.yml
          git diff --exit-code
      -
        name: HTML generation runs
        run: ./contriblog html examples/contributions.yml
      -
        name: RSS generation runs
        run: ./contriblog RSS examples/contributions.yml
